# Generated by Django 5.1.6 on 2025-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('admission_number', models.PositiveIntegerField(unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=10)),
                ('guardian_contact', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
