# Generated by Django 5.1.6 on 2025-03-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
